Name: Application Layer Protocol
Tactic: Command and Control
Description:
  Description:
  - 'Adversaries may communicate using OSI application layer protocols to avoid detection/network
    filtering by blending in with existing traffic. Commands to the remote system,
    and often the results of those commands, will be embedded within the protocol
    traffic between the client and server. Adversaries may utilize many different
    protocols, including those used for web browsing, transferring files, electronic
    mail, or DNS. For connections that occur internally within an enclave (such as
    those between a proxy or pivot node and other nodes), commonly used protocols
    are SMB, SSH, or RDP. '
Information:
  ID: T1071
  Sub-techniques:
  - T1071.001
  - T1071.002
  - T1071.003
  - T1071.004
  Tactic: Command and Control
  Platforms: Linux, Windows, macOS
  Contributors: Duane Michael
  Version: '2.1'
  Created: 31 May 2017
  Last Modified: 11 April 2023
