Name: Non-Application Layer Protocol
Tactic: Command and Control
Description:
  Description:
  - Adversaries may use an OSI non-application layer protocol for communication between
    host and C2 server or among infected hosts within a network. The list of possible
    protocols is extensive.[1] Specific examples include use of network layer protocols,
    such as the Internet Control Message Protocol (ICMP), transport layer protocols,
    such as the User Datagram Protocol (UDP), session layer protocols, such as Socket
    Secure (SOCKS), as well as redirected/tunneled protocols, such as Serial over
    LAN (SOL).ICMP communication between hosts is one example.[2] Because ICMP is
    part of the Internet Protocol Suite, it is required to be implemented by all IP-compatible
    hosts.[3] However, it is not as commonly monitored as other Internet Protocols
    such as TCP or UDP and may be used by adversaries to hide communications.
Information:
  ID: T1095
  Sub-techniques: []
  Tactic: Command and Control
  Platforms: Linux, Network, Windows, macOS
  Contributors: Duane Michael; Ryan Becwar
  Version: '2.3'
  Created: 31 May 2017
  Last Modified: 29 September 2023
