Name: Office Application Startup
Tactic: Persistence
Description:
  Description:
  - Adversaries may leverage Microsoft Office-based applications for persistence between
    startups. Microsoft Office is a fairly common application suite on Windows-based
    operating systems within an enterprise network. There are multiple mechanisms
    that can be used with Office for persistence when an Office-based application
    is started; this can include the use of Office Template Macros and add-ins.A variety
    of features have been discovered in Outlook that can be abused to obtain persistence,
    such as Outlook rules, forms, and Home Page.[1] These persistence mechanisms can
    work within Outlook or be used through Office 365.[2]
Information:
  ID: T1137
  Sub-techniques:
  - T1137.001
  - T1137.002
  - T1137.003
  - T1137.004
  - T1137.005
  - T1137.006
  Tactic: Persistence
  Platforms: Office 365, Windows
  Permissions Required: Administrator, User
  Contributors: Loic Jaquemet; Microsoft Threat Intelligence Center (MSTIC); Nick
    Carr, Mandiant; Praetorian; Ricardo Dias; Sahar Shukrun
  Version: '1.3'
  Created: 14 December 2017
  Last Modified: 15 October 2021
