Name: Data from Configuration Repository
Tactic: Collection
Description:
  Description:
  - Adversaries may collect data related to managed devices from configuration repositories.
    Configuration repositories are used by management systems in order to configure,
    manage, and control data on remote systems. Configuration repositories may also
    facilitate remote access and administration of devices.Adversaries may target
    these repositories in order to collect large quantities of sensitive system administration
    data. Data from configuration repositories may be exposed by various protocols
    and software and can store a wide variety of data, much of which may align with
    adversary Discovery objectives.[1][2]
Information:
  ID: T1602
  Sub-techniques:
  - T1602.001
  - T1602.002
  Tactic: Collection
  Platforms: Network
  Version: '1.0'
  Created: 19 October 2020
  Last Modified: 19 April 2022
